ENV_NAME = "mysql57"
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = ENV_NAME
  config.vm.network "private_network", ip: "192.168.42.17"

  config.vm.define ENV_NAME do |node|
    node.vm.provider :virtualbox do |vb|
      vb.name = ENV_NAME
      vb.memory = "1024"
    end
  end

  config.vm.provision "shell", path: "install.sh"
end
